# Generated by Django 4.1.2 on 2023-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('CurrentPoser', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
