# Generated by Django 4.1.2 on 2023-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
